version: '3.8'
services:
  db:
    image: mariadb:11.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: car_listings
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: .
    command: node server/index.js
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: example
      DB_NAME: car_listings
    ports:
      - '3001:3001'
    depends_on:
      - db

volumes:
  db_data:
